# Generated by Django 4.0.2 on 2022-02-28 01:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0002_urls_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urls",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 2, 28, 1, 0, 11, 974347, tzinfo=utc)
            ),
        ),
    ]
